baseurl = "https://www.zhyuntao.com/"
title = "Black & Light"
author = "张云涛"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Black & Light"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://zhyuntao.com/davidhampgonsalves/about"
[[menu.main]]
    name = "Projects"
    url  = "https://zhyuntao.com/davidhampgonsalves/projects"
[[menu.main]]
    name = "Resume"
    url  = "https://zhyuntao.com/davidhampgonsalves/about/resume"

